# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: base-transfer-tracker
networks:
- id: 8453
  start_block: 33000000
  contracts:
  - name: FiatTokenProxy
    address:
    - 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
    handler: src/EventHandlers.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 value)
unordered_multichain_mode: true
